repositories:
    - name: dts
      url: https://helm.dts-stn.com
    # helm-git powered repository: You can treat any Git repository as a charts repository
    - name: policy-dev-eng-dts-csps
      url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/policy-dev-eng-dts-csps@helm/charts?ref=main
{{- if or (eq .Environment.Name "prod-blue") (eq .Environment.Name "prod-green") }}    
context: EsDCDTSRG-K8S
{{ else }}
context: EsDCDTSDevRG-K8S
{{ end }}
   
environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    pondrd:
    #USING INT, MAIN AND SPRINT TO REFLECT OUR INTEGRATION (PR VERSION), MAIN (REFLECTING MAIN BRANCH), SPRINT (STATIC RELEASE VERSION FOR SPRINT REVIEW)
    int:
    main:
    sprint:
    prod-blue:
    prod-green: 

releases:
# Policy Diff Engine
  - name: policy-dev-eng-dts-csps-{{ .Environment.Name }}
    chart: policy-dev-eng-dts-csps/policy-dev-eng-dts-csps
    version: 0.0.3
    values:
      - overrides/policy-dev-eng-dts-csps.yaml.gotmpl
    labels:
        category: dts
        app: policy-dev-eng-dts-csps
        tier: server
    namespace: policy-dev-eng-dts-csps-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false