repositories:
    # helm-git powered repository: You can treat any Git repository as a charts repository
    - name: policy-diff
      url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/policy-dev-eng-dts-csps@helm/charts?ref=main
   
environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    pondrd:
    #USING INT, MAIN AND SPRINT TO REFLECT OUR INTEGRATION (PR VERSION), MAIN (REFLECTING MAIN BRANCH), SPRINT (STATIC RELEASE VERSION FOR SPRINT REVIEW)
    int:
    main:
    sprint:
    prod-blue:
    prod-green: 

releases:
# Policy Diff Engine
  - name: policy-diff-{{ .Environment.Name }}
    chart: ../helm/charts/policy-diff
    version: 0.0.3
    values:
      - overrides/policy-diff.yaml.gotmpl
    labels:
        category: dts
        app: policy-diff
        tier: server
    namespace: policy-diff-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false
